app:start.c tank.c ui.c loop.c framework.c event_dispatcher.c tank_factory.c
	gcc -Wint-to-pointer-cast -o app event_dispatcher.c tank_factory.c start.c tank.c ui.c loop.c framework.c -I. -L/home/yangu/allegro5/lib -lallegro -lallegro_main -lallegro_image
